mlp_defaults:
  solver: 'adam'
  alpha: 0.0001
  hidden_layer_sizes: (256, 512)
  learning_rate: 'adaptive'
  max_iter: 100000
  learning_rate_init: 0.001
  verbose: 0
  random_state: 1

xgb_defaults:
  # Standard XGBClassifier values
  base_score: 0.5 # default XGBClassifier value
  booster: 'gbtree' # default XGBClassifier value
  colsample_bylevel: 1 # default XGBClassifier value
  colsample_bynode: 1 # default XGBClassifier value
  colsample_bytree: 0.8 # default 1
  gamma: 1 # default 0
  learning_rate: 0.1 # default XGBClassifier value
  max_delta_step: 0 # default XGBClassifier value
  max_depth: 3 # default XGBClassifier value MARS_Developer clf_defaults.yaml = 9
  min_child_weight: 1 # default XGBClassifier value MARS_Developer clf_defaults.yaml = 4
  missing: None # default XGBClassifier value
  n_estimators: 2000 # default 100
  nthread: -1 # default 1
  objective: 'binary:logistic' # default XGBClassifier value
  reg_alpha: 0 # default XGBClassifier value
  reg_lambda: 1 # default XGBClassifier value
  scale_pos_weight: 1 # default XGBClassifier value
  seed: 33 # default 0
  subsample: 0.8 # default 1
  verbosity: 2 # default 1
  # extra parameters
  tree_method: 'hist' # default 'auto'
  max_bin: 256 # default xgboost value 
  random_state': 42